### ISSUE TITLE
Cursor misplaced at certain font sizes

### ISSUE THREAD

**Issue by imso** [RyanHope/wTerm#18]
When using font sizes of 8 or 11, the cursor seems to move right an extra pixel for each character typed.

**Comment by dtzWill** [comment]
This was fixed as part of the GL backend work and shouldn't happen any longer (aka should be fixed in next release since that's been pulled in).
Despite using a fixed-width font it appears for certain font-sizes you can't count on the length of a SDL_TTF-rendered string to always be exactly a multiple of a single character.  I wasn't able to figure out why, so we now explicitly position each character, which resolves the issue.
(It is for this reason https://github.com/PuffTheMagic/wTerm/commit/c00d25f7794f6ccc35e30226d28344aaf3aa283f#L3R201 blits each character to a particular location manually instead of simply rendering the entire set of printable characters in one go)
