### ISSUE TITLE
Pre3 QWERTZ dot produces backspace

### ISSUE THREAD

**Issue by Garfonso** [RyanHope/wTerm#86]
Hi,

on my Pre3 the dot (left of the spacebar) only produces a backspace. So I can't type cd .. (just an example). I don't think that is a feature, because the backspace key is fine, right?
Is this connected to my QWERTZ keyboard layout?

Cheers
Garfonso

**Comment by Goyena** [comment]
Hi, 
the same thing happens on my American (AT&T) Pre 3. Garfonso, the dot key is to the right of the spacebar (bottom row has five keys: SHIFT   @/0   SPACE    .    sym). I push dot and get a backspace.

And "cd.." was the first (and last) command I tried. 

Beta testing was gonna be a bit hard without the dot.

**Comment by Garfonso** [comment]
yeah, you're right of course the dot is right to the spacebar. :)
I could handle around this with cd / and then typing the full path, because the original path was not of much use to my anyways ( /var/.../wTerm something like that). 

I'd like to get this issue resolved. Because the virtual tab key makes tab completion much more useful than those cryptic key combinations xterm uses, which I regularly forget. :(

@devs: Any idea where this might come from?

**Comment by directhex** [comment]
Same behaviour on a UK QWERTY Pre 3.

**Comment by Brybry** [comment]
I believe we've fixed this for the next release but the behavior will probably be that dot key is 'alt' and orange key + dot/key is '.'

Of course this is not set in stone and I believe that there are plans to make it configurable in preferences.

For the curious the problem was that the KeyboardEvent had a unicode/keyIdentifier for delete (0x7F or 127) and the javascript keycode for dot/period (190).
