### ISSUE TITLE
Pre+ displays wrong characters

### ISSUE THREAD

**Issue by ragingmind** [RyanHope/wTerm#87]
VZW Pre+ with webOS2.1.0 and wTerm 0.3.999-2.  When typing into the terminal many of the keyboard characters show up as letters different than expected in the term and characters printed in the term are different.

For example trying to run ssh:  it shows up as ssi in the term, but enter still runs the command and I see the default usage message.  Many of the letters are switched making it look like gibberish.

**Comment by stbuehler** [comment]
Yes, same with Pre- and webOS 2.1.

The problem lies in the opengl specification; we transfer the character values as color in a texture to the shader, and the specifications allows the implementation to throw away bits from the color value.
Right now we use 7 bits (in the raw texture data we have 8 bits), and it seems this is too much for the old devices.

If we want to support xterm-256 color style, we probably need a second texture anyway, so we could use less bits from one color channel.

You can use menu 3 in vttest (character sets) to see what chars are missing and how they are shifted.
